spring:
  application:
    name: turing
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #show_sql: true
        #format_sql: true
        default_batch_fetch_size: 1000
#Swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
server:
  port: 8080
#JWT

#S3

#GPT
gpt:
  model: ${GPT_MODEL}
  api:
    key: ${GPT_API_KEY}
    url: ${GPT_URL}